# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'essamalmohammadi/dotnet-servercore'
  DECODE_PERCENTS: true # https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md

stages:
- stage: Build_and_Push
  displayName: Build & Push images
  jobs:
  - job: Build_and_Push
    displayName: Build & Push
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: Build and Push .NET Core 2.1 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore21.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          2.1-aspnetcore-runtime-ltsc2019
    - task: Docker@2
      displayName: Build and Push .NET Core 2.2 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore22.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          2.2-aspnetcore-runtime-ltsc2019
    - task: Docker@2
      displayName: Build and Push .NET Core 3.0 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore30.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          3.0-aspnetcore-runtime-ltsc2019
    - task: Docker@2
      displayName: Build and Push .NET Core 3.1 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore31.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          3.1-aspnetcore-runtime-ltsc2019
          lts
    - task: Docker@2
      displayName: Build and Push .NET 5 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore50.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          5.0-aspnetcore-runtime-ltsc2019
    - task: Docker@2
      displayName: Build and Push .NET 6 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore60.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          6.0-aspnetcore-runtime-ltsc2019
          latest-lts
    - task: Docker@2
      displayName: Build and Push .NET 7 image
      inputs:
        command: buildAndPush
        Dockerfile: '**/netcore70.dockerfile'
        repository: $(imageName)
        containerRegistry: Docker Hub
        tags: |
          7.0-aspnetcore-runtime-ltsc2019
          sts
          latest
